# Generated by Django 3.2.23 on 2024-01-23 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Node',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=255)),
                ('name', models.CharField(max_length=255)),
                ('labels', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False)),
                ('relation_type', models.CharField(max_length=255)),
                ('relation_name', models.CharField(max_length=255)),
                ('from_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_node', to='bd_schema_plugin.node')),
                ('to_node', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_node', to='bd_schema_plugin.node')),
            ],
        ),
    ]
