# Generated by Django 3.2.23 on 2024-01-25 05:46

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_schema_plugin', '0002_auto_20240125_0253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='labels',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=20), blank=True, default=[], size=None),
        ),
    ]
