# Generated by Django 3.2.23 on 2024-01-25 23:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_schema_plugin', '0005_alter_node_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='node',
            name='property',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
