# Generated by Django 3.2.23 on 2024-01-25 23:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_schema_plugin', '0006_alter_node_property'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='node',
            name='name',
        ),
    ]
