# Generated by Django 3.2.23 on 2024-01-27 00:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_schema_plugin', '0007_remove_node_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='property',
            new_name='properties',
        ),
    ]
