# Generated by Django 3.2.23 on 2024-01-27 00:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bd_schema_plugin', '0008_rename_property_node_properties'),
    ]

    operations = [
        migrations.RenameField(
            model_name='node',
            old_name='type',
            new_name='types',
        ),
    ]
