# Generated by Django 3.2.23 on 2024-01-27 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_schema_plugin', '0009_rename_type_node_types'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='relationship',
            name='relation_name',
        ),
        migrations.AddField(
            model_name='relationship',
            name='properties',
            field=models.JSONField(default=''),
        ),
    ]
