# Generated by Django 3.2.23 on 2024-01-27 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bd_schema_plugin', '0010_auto_20240127_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relationship',
            name='properties',
            field=models.JSONField(default=dict),
        ),
    ]
